import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CheckCircle, Clock, Eye, FilePlus2, RefreshCw, Trash2, Upload, XCircle } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Modal, ModalContent } from '@/components/ui/modal';
import { ConfirmDialog } from '@/components/ui/confirm-dialog';
import ErrorModal from '@/components/modals/ErrorModal';
import SuccessModal from '@/components/modals/SuccessModal';
import DocumentDetailsDialog from './DocumentDetailsDialog';
import { documentService, type Document, type DocumentRequirement } from '@/services/documentService';

const DocumentsManager = ({ nupcan }: { nupcan: string }) => {
  const queryClient = useQueryClient();
  const [uploadTarget, setUploadTarget] = useState<DocumentRequirement | null | undefined>();
  const [replaceTarget, setReplaceTarget] = useState<Document | null>(null);
  const [details, setDetails] = useState<{ document: Document; supplemental: boolean } | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<Document | null>(null);
  const [optionalName, setOptionalName] = useState(''); const [file, setFile] = useState<File | null>(null);
  const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  const query = useQuery({ queryKey: ['document-checklist', nupcan], queryFn: () => documentService.getChecklist(nupcan) });
  const refresh = () => queryClient.invalidateQueries({ queryKey: ['document-checklist', nupcan] });
  const closeUpload = () => { setUploadTarget(undefined); setReplaceTarget(null); setOptionalName(''); setFile(null); };
  const pickFile = (event: React.ChangeEvent<HTMLInputElement>) => { const next=event.target.files?.[0]||null; if(next&&next.size>10*1024*1024){setError('Le fichier dépasse 10 Mo.');event.target.value='';return;} setFile(next); };
  const upload = useMutation({ mutationFn:async()=>{if(!file)throw new Error('Sélectionnez un fichier.');if(uploadTarget===null&&!optionalName.trim())throw new Error('Indiquez le nom du document.');const form=new FormData();form.append('file',file);form.append('nupcan',nupcan);form.append('nomdoc',uploadTarget?.nom||optionalName.trim());if(uploadTarget)form.append('requirement_id',uploadTarget.id);return documentService.uploadDocument(form);},onSuccess:()=>{setSuccess('Document envoyé en validation.');closeUpload();refresh();},onError:(e:Error)=>setError(e.message)});
  const replace = useMutation({ mutationFn:async()=>{if(!file||!replaceTarget)throw new Error('Sélectionnez le nouveau fichier.');const form=new FormData();form.append('file',file);form.append('nomdoc',replaceTarget.nomdoc);return documentService.replaceDocument(replaceTarget.id,form);},onSuccess:()=>{setSuccess('Document remplacé et remis en attente de validation.');closeUpload();setDetails(null);refresh();},onError:(e:Error)=>setError(e.message)});
  const remove = useMutation({ mutationFn:(id:string)=>documentService.deleteDocument(nupcan,id),onSuccess:()=>{setSuccess('Document facultatif supprimé.');setDeleteTarget(null);setDetails(null);refresh();},onError:(e:Error)=>setError(e.message)});
  const rename = async (document:Document,name:string)=>{try{await documentService.renameDocument(document.id,name);setSuccess('Libellé du document modifié.');setDetails(null);await refresh();}catch(e:any){setError(e.message||'Modification impossible');throw e;}};
  const badge=(status?:Document['document_statut'])=>status==='valide'?<Badge className="bg-green-100 text-green-800"><CheckCircle className="mr-1 h-3 w-3"/>Validé</Badge>:status==='rejete'?<Badge className="bg-red-100 text-red-800"><XCircle className="mr-1 h-3 w-3"/>Rejeté</Badge>:<Badge className="bg-amber-100 text-amber-800"><Clock className="mr-1 h-3 w-3"/>En attente</Badge>;
  const actions=(document:Document,supplemental=false)=><div className="flex shrink-0 flex-wrap gap-2"><Button variant="outline" size="sm" onClick={()=>setDetails({document,supplemental})}><Eye className="mr-2 h-4 w-4"/>Visualiser / éditer</Button><Button size="sm" onClick={()=>{setReplaceTarget(document);setFile(null);}}><RefreshCw className="mr-2 h-4 w-4"/>Changer le fichier</Button>{supplemental&&<Button variant="destructive" size="icon" onClick={()=>setDeleteTarget(document)} aria-label="Supprimer"><Trash2 className="h-4 w-4"/></Button>}</div>;
  if(query.isLoading)return <div className="py-12 text-center">Chargement des documents…</div>;
  if(query.isError||!query.data)return <div className="py-12 text-center text-red-600">Impossible de charger les documents.</div>;
  const data=query.data;
  return <div className="space-y-6">
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Requis',data.summary.required],['Manquants',data.summary.missing],['Validés',data.summary.approved],['Rejetés',data.summary.rejected]].map(([label,value])=><Card key={String(label)}><CardContent className="p-4"><p className="text-2xl font-bold">{value}</p><p className="text-sm text-muted-foreground">{label}</p></CardContent></Card>)}</div>
    <Card><CardHeader><CardTitle>Documents demandés ({data.checklist.length})</CardTitle></CardHeader><CardContent className="space-y-3">{!data.checklist.length&&<p className="rounded-md border border-dashed py-9 text-center text-muted-foreground">Aucun document configuré pour ce concours.</p>}{data.checklist.map(({requirement,document})=><div key={requirement.id} className="flex flex-col justify-between gap-3 rounded-sm border p-4 sm:flex-row sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className="font-medium">{requirement.nom}</span>{requirement.obligatoire&&<Badge variant="outline">Obligatoire</Badge>}{document&&badge(document.document_statut)}</div><p className="text-sm text-muted-foreground">{requirement.description||'Pièce définie par le concours'}</p><p className="mt-1 font-mono text-[11px] text-muted-foreground">ID exigence : {requirement.id}{document ? ` · ID document : ${document.id}` : ''}</p></div>{document?actions(document):<Button size="sm" onClick={()=>{setUploadTarget(requirement);setFile(null);}}><Upload className="mr-2 h-4 w-4"/>Téléverser</Button>}</div>)}</CardContent></Card>
    <Card><CardHeader><CardTitle className="flex flex-wrap items-center justify-between gap-3"><span>Documents supplémentaires ({data.supplemental.length})</span><Button size="sm" variant="outline" onClick={()=>{setUploadTarget(null);setFile(null);}}><FilePlus2 className="mr-2 h-4 w-4"/>Ajouter une pièce facultative</Button></CardTitle></CardHeader><CardContent className="space-y-3">{!data.supplemental.length&&<p className="py-5 text-center text-sm text-muted-foreground">Aucun document supplémentaire.</p>}{data.supplemental.map(document=><div key={document.id} className="flex flex-col justify-between gap-3 rounded-md border p-4 sm:flex-row sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className="font-medium">{document.nomdoc}</span>{badge(document.document_statut)}</div><p className="text-sm text-muted-foreground">{document.nom_fichier||document.type}</p><p className="mt-1 font-mono text-[11px] text-muted-foreground">ID : {document.id}</p></div>{actions(document,true)}</div>)}</CardContent></Card>
    <Modal open={uploadTarget!==undefined} onOpenChange={open=>!open&&closeUpload()}><ModalContent><div className="space-y-4 p-6"><h2 className="text-xl font-bold">{uploadTarget?`Téléverser : ${uploadTarget.nom}`:'Ajouter un document facultatif'}</h2>{uploadTarget===null&&<div><label className="text-sm font-medium">Nom du document</label><Input value={optionalName} onChange={e=>setOptionalName(e.target.value)} placeholder="Ex. Lettre de recommandation"/></div>}<div><label className="text-sm font-medium">Fichier (PDF ou image, 10 Mo max.)</label><Input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={pickFile}/></div><div className="flex gap-2"><Button disabled={!file||upload.isPending} onClick={()=>upload.mutate()}>{upload.isPending?'Envoi…':'Téléverser'}</Button><Button variant="outline" onClick={closeUpload}>Annuler</Button></div></div></ModalContent></Modal>
    <Modal open={!!replaceTarget} onOpenChange={open=>!open&&closeUpload()}><ModalContent><div className="space-y-4 p-6"><h2 className="text-xl font-bold">Remplacer {replaceTarget?.nomdoc}</h2>{replaceTarget?.commentaire_validation&&<div className="rounded-md bg-red-50 p-3 text-sm text-red-700">Motif : {replaceTarget.commentaire_validation}</div>}<Input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={pickFile}/><div className="flex gap-2"><Button disabled={!file||replace.isPending} onClick={()=>replace.mutate()}>{replace.isPending?'Remplacement…':'Remplacer'}</Button><Button variant="outline" onClick={closeUpload}>Annuler</Button></div></div></ModalContent></Modal>
    <DocumentDetailsDialog document={details?.document||null} supplemental={details?.supplemental} onClose={()=>setDetails(null)} onRename={name=>rename(details!.document,name)} onReplace={document=>{setDetails(null);setReplaceTarget(document);setFile(null);}}/>
    <ConfirmDialog open={!!deleteTarget} onOpenChange={open=>!open&&setDeleteTarget(null)} title="Supprimer ce document ?" description={`La pièce facultative « ${deleteTarget?.nomdoc||''} » sera supprimée définitivement.`} confirmLabel="Supprimer" pending={remove.isPending} onConfirm={()=>deleteTarget&&remove.mutate(deleteTarget.id)}/>
    <ErrorModal title="Erreur documentaire" isOpen={!!error} onClose={()=>setError('')} message={error}/><SuccessModal title="Opération réussie" isOpen={!!success} onClose={()=>setSuccess('')} message={success}/>
  </div>;
};
export default DocumentsManager;
