const mongoose = require('mongoose');
const E = require('../../utils/enums');
const { Schema, model, models } = mongoose;
const opts = { timestamps: true };
const legacy = { legacyId: { type: Number, sparse: true, index: true } };
const ref = name => ({ type: Schema.Types.ObjectId, ref: name, index: true });
const make = (name, schema, indexes = []) => {
  indexes.forEach(([fields, options]) => schema.index(fields, options));
  return models[name] || model(name, schema);
};

const Establishment = make('Establishment', new Schema({ ...legacy, name: { type: String, required: true, trim: true }, address: String, phone: String, email: String, code: { type: String, trim: true, uppercase: true }, provinceId: ref('Province'), active: { type: Boolean, default: true } }, opts), [[{ code: 1 }, { unique: true, sparse: true }]]);
const Program = make('Program', new Schema({ ...legacy, name: { type: String, required: true, trim: true }, code: { type: String, trim: true, uppercase: true }, educationLevelId: ref('EducationLevel'), establishmentIds: [ref('Establishment')] }, opts), [[{ name: 'text', code: 'text' }, {}]]);
const Subject = make('Subject', new Schema({ ...legacy, name: { type: String, required: true }, code: String, coefficient: { type: Number, min: 0 }, programIds: [ref('Program')] }, opts));
const Contest = make('Contest', new Schema({ ...legacy, title: { type: String, required: true, trim: true }, slug: { type: String, required: true, lowercase: true }, description: String, establishmentId: ref('Establishment'), educationLevelId: ref('EducationLevel'), programIds: [ref('Program')], opensAt: Date, closesAt: Date, fee: { type: Number, min: 0, default: 0 }, currency: { type: String, default: 'XAF' }, status: { type: String, enum: ['draft','open','closed','archived'], default: 'draft' }, session: String, contestType: String, maximumAge: Number, totalPlaces: Number, trainingDuration: String, awardedDiploma: String, resultsPublishedAt: Date, coursesStartAt: Date, acceptedBacSeries: [String], selectionCriteria: Schema.Types.Mixed, registrationSteps: Schema.Types.Mixed, eligibilityConditions: Schema.Types.Mixed, contactEmail: String, contactPhone: String, examLocation: String, additionalInformation: String }, opts), [[{ slug: 1 }, { unique: true }], [{ status: 1, closesAt: 1 }, {}], [{ title: 'text', description: 'text' }, {}]]);
const Administrator = make('Administrator', new Schema({ ...legacy, firstName: String, lastName: String, email: { type: String, required: true, lowercase: true, trim: true }, passwordHash: { type: String, required: true, select: false }, mustChangePassword: { type: Boolean, default: false }, passwordChangedAt: Date, role: { type: String, enum: E.ADMIN_ROLES, default: 'reviewer' }, subAdminRole: { type: String, enum: E.SUB_ADMIN_ROLES }, permissions: [{ type: String, enum: E.ADMIN_PERMISSIONS }], establishmentIds: [ref('Establishment')], createdBy: ref('Administrator'), active: { type: Boolean, default: true }, lastLoginAt: Date }, opts), [[{ email: 1 }, { unique: true }]]);
const Candidate = make('Candidate', new Schema({ ...legacy, username: { type: String, lowercase: true, trim: true }, passwordHash: { type: String, select: false }, accountPhone: { type: String }, nipcan: { type: String, uppercase: true, trim: true }, firstName: { type: String, required: true, trim: true }, lastName: { type: String, required: true, trim: true }, birthDate: Date, birthPlace: { type: String, trim: true }, phone: { type: String, required: true, trim: true }, email: { type: String, lowercase: true, trim: true }, nationalId: { type: String, trim: true }, photoData: String, originProvinceId: ref('Province'), currentProvinceId: ref('Province'), assignedProvinceId: ref('Province'), verificationCodeHash: { type: String, select: false } }, opts), [[{ username: 1 }, { unique: true, sparse: true }], [{ accountPhone: 1 }, { unique: true, sparse: true }], [{ nipcan: 1 }, { unique: true, sparse: true }], [{ phone: 1 }, {}], [{ email: 1 }, { unique: true, partialFilterExpression: { email: { $type: 'string', $gt: '' } } }], [{ firstName: 'text', lastName: 'text', phone: 'text' }, {}]]);
const statusHistory = new Schema({ status: String, reason: String, changedBy: ref('Administrator'), at: { type: Date, default: Date.now } }, { _id: false });
const Application = make('Application', new Schema({ ...legacy, candidateId: { ...ref('Candidate'), required: true }, contestId: { ...ref('Contest'), required: true }, programId: { ...ref('Program'), required: true }, nupcan: { type: String, required: true, uppercase: true, trim: true }, status: { type: String, enum: E.APPLICATION_STATUS, default: 'draft', index: true }, completedSteps: [{ type: String, enum: ['candidate','documents','payment','confirmation'] }], documentStatus: { type: String, enum: E.DOCUMENT_STATUS, default: 'pending' }, paymentStatus: { type: String, enum: E.PAYMENT_STATUS, default: 'pending' }, contestSnapshot: { title: String, fee: Number, currency: String, establishmentName: String, programName: String }, statusHistory: [statusHistory], submittedAt: Date }, opts), [[{ nupcan: 1 }, { unique: true }], [{ candidateId: 1, contestId: 1 }, { unique: true }], [{ contestId: 1, status: 1, createdAt: -1 }, {}]]);
const applicationDocumentSchema = new Schema({ ...legacy, applicationId: { ...ref('Application'), required: true }, candidateId: { ...ref('Candidate'), required: true }, requirementId: ref('DocumentRequirement'), type: { type: String, required: true }, required: { type: Boolean, default: true }, storageKey: { type: String, required: true, unique: true }, contentData: String, originalName: String, safeName: String, mimeType: String, size: Number, checksum: String, status: { type: String, enum: E.DOCUMENT_STATUS, default: 'uploaded' }, aiStatus: { type: String, enum: ['disabled', 'pending', 'running', 'completed', 'failed'], default: 'pending' }, aiRecommendation: { type: String, enum: ['approve', 'reject', 'review'] }, aiConfidence: { type: Number, min: 0, max: 1 }, aiReason: String, aiAnalyzedAt: Date, aiStartedAt: Date, aiRunToken: String, aiError: String, rejectionReason: String, retentionUntil: Date, version: { type: Number, default: 1 } }, opts);
applicationDocumentSchema.pre('save', function resetDocumentAnalysis(next) {
  if (this.isModified('contentData')) {
    this.aiRunToken = undefined; this.aiStartedAt = undefined; this.aiStatus = 'pending'; this.aiRecommendation = undefined; this.aiConfidence = undefined; this.aiReason = undefined; this.aiAnalyzedAt = undefined; this.aiError = undefined;
  }
  next();
});
applicationDocumentSchema.post('save', document => {
  if (document.status === 'uploaded' && ['pending', 'disabled'].includes(document.aiStatus)) require('../../services/documentAiService').queueDocumentAnalysis(document._id);
});
const ApplicationDocument = make('ApplicationDocument', applicationDocumentSchema, [[{ applicationId: 1, type: 1, version: -1 }, {}], [{ applicationId: 1, requirementId: 1 }, { unique: true, sparse: true }], [{ aiStatus: 1, createdAt: -1 }, {}]]);
const Payment = make('Payment', new Schema({ ...legacy, applicationId: { ...ref('Application'), required: true }, candidateId: ref('Candidate'), provider: { type: String, enum: ['airtel_money','moov','moov_money','cinetpay','development'], required: true }, paymentReference: { type: String, required: true }, transactionId: String, amount: { type: Number, required: true, min: 0 }, currency: { type: String, default: 'XAF' }, status: { type: String, enum: E.PAYMENT_STATUS, default: 'pending' }, events: [{ eventId: String, type: String, receivedAt: { type: Date, default: Date.now }, payloadHash: String }] }, opts), [[{ paymentReference: 1 }, { unique: true }], [{ transactionId: 1 }, { unique: true, sparse: true }], [{ applicationId: 1, createdAt: -1 }, {}]]);
const simple = (name, fields, indexes=[]) => make(name, new Schema({ ...legacy, ...fields }, opts), indexes);
const Notification = simple('Notification', { candidateId: ref('Candidate'), recipientAdministratorId: ref('Administrator'), applicationId: ref('Application'), legacyNupcan: { type: String, trim: true }, title: String, body: String, channel: { type: String, enum: ['in_app','email','sms'] }, readAt: Date }, [[{ candidateId: 1, createdAt: -1 }, {}], [{ recipientAdministratorId: 1, readAt: 1, createdAt: -1 }, {}], [{ legacyNupcan: 1, createdAt: -1 }, {}]]);
const Message = simple('Message', { applicationId: ref('Application'), candidateId: ref('Candidate'), administratorId: ref('Administrator'), legacyNupcan: { type: String, trim: true }, subject: String, senderType: { type: String, enum: ['candidate','administrator'] }, body: { type: String, required: true }, readAt: Date });
const SupportRequest = simple('SupportRequest', { candidateId: ref('Candidate'), applicationId: ref('Application'), subject: String, body: String, status: { type: String, enum: ['open','in_progress','resolved','closed'], default: 'open' } });
const AuditLog = simple('AuditLog', { actorId: ref('Administrator'), action: { type: String, required: true }, entityType: String, entityId: Schema.Types.ObjectId, establishmentId: ref('Establishment'), correlationId: String, metadata: Schema.Types.Mixed }, [[{ createdAt: -1 }, {}], [{ actorId: 1, createdAt: -1 }, {}]]);
const Session = simple('Session', { administratorId: ref('Administrator'), candidateId: ref('Candidate'), actorType: { type: String, enum: ['administrator','candidate'], required: true }, tokenHash: { type: String, required: true }, expiresAt: { type: Date, required: true }, revokedAt: Date }, [[{ expiresAt: 1 }, { expireAfterSeconds: 0 }]]);
const Counter = make('Counter', new Schema({ _id: String, seq: { type: Number, default: 0 } }));
const Province = simple('Province', { name: { type: String, required: true, trim: true }, code: { type: String, required: true, uppercase: true, trim: true }, cities: [{ type: String, trim: true }], active: { type: Boolean, default: true } }, [[{ code: 1 }, { unique: true }], [{ name: 1 }, { unique: true }]]);
const EducationLevel = simple('EducationLevel', { name: { type: String, required: true, trim: true }, code: { type: String, required: true, uppercase: true, trim: true }, description: { type: String, trim: true }, rank: { type: Number, min: 0 }, active: { type: Boolean, default: true } }, [[{ code: 1 }, { unique: true }]]);
const ContestProgram = simple('ContestProgram', { contestId: { ...ref('Contest'), required: true }, programId: { ...ref('Program'), required: true }, establishmentId: ref('Establishment'), educationLevelId: ref('EducationLevel'), capacity: { type: Number, min: 0 }, fee: { type: Number, min: 0 }, opensAt: Date, closesAt: Date, eligibilityRules: Schema.Types.Mixed, active: { type: Boolean, default: true } }, [[{ contestId: 1, programId: 1, establishmentId: 1 }, { unique: true }], [{ contestId: 1, active: 1 }, {}]]);
const ProgramSubject = simple('ProgramSubject', { programId: { ...ref('Program'), required: true }, subjectId: { ...ref('Subject'), required: true }, contestId: ref('Contest'), coefficient: { type: Number, min: 0, required: true }, required: { type: Boolean, default: true }, minimumScore: { type: Number, min: 0 } }, [[{ programId: 1, subjectId: 1, contestId: 1 }, { unique: true }]]);
const DocumentRequirement = simple('DocumentRequirement', { contestId: { ...ref('Contest'), required: true }, programId: ref('Program'), code: { type: String, required: true, uppercase: true, trim: true }, name: { type: String, required: true }, description: String, aiValidationInstructions: String, aiRejectionRules: String, validationInstructions: { type: String, trim: true, maxlength: 3000 }, rejectionInstructions: { type: String, trim: true, maxlength: 3000 }, required: { type: Boolean, default: true }, acceptedMimeTypes: [{ type: String }], maxSizeBytes: { type: Number, min: 1 }, exampleStorageKey: String, exampleContentData: String, exampleOriginalName: String, exampleMimeType: String, exampleSize: Number, active: { type: Boolean, default: true } }, [[{ contestId: 1, programId: 1, code: 1 }, { unique: true }]]);
const Grade = simple('Grade', { applicationId: { ...ref('Application'), required: true }, subjectId: { ...ref('Subject'), required: true }, score: { type: Number, required: true, min: 0 }, maximumScore: { type: Number, required: true, min: 1 }, coefficient: { type: Number, min: 0, default: 1 }, enteredBy: ref('Administrator'), validatedBy: ref('Administrator'), validatedAt: Date }, [[{ applicationId: 1, subjectId: 1 }, { unique: true }]]);
const PaymentEvent = simple('PaymentEvent', { paymentId: { ...ref('Payment'), required: true }, provider: { type: String, required: true }, eventId: { type: String, required: true }, eventType: { type: String, required: true }, signatureValid: { type: Boolean, required: true }, payloadHash: { type: String, required: true }, statusBefore: String, statusAfter: String, processedAt: Date, processingError: String }, [[{ provider: 1, eventId: 1 }, { unique: true }], [{ paymentId: 1, createdAt: 1 }, {}]]);
const Receipt = simple('Receipt', { applicationId: { ...ref('Application'), required: true }, paymentId: { type: Schema.Types.ObjectId, ref: 'Payment', required: true }, receiptNumber: { type: String, required: true, uppercase: true }, storageKey: { type: String, required: true }, checksum: String, issuedAt: { type: Date, default: Date.now } }, [[{ receiptNumber: 1 }, { unique: true }], [{ paymentId: 1 }, { unique: true }], [{ storageKey: 1 }, { unique: true }]]);
const VerificationCode = simple('VerificationCode', { candidateId: ref('Candidate'), applicationId: ref('Application'), purpose: { type: String, enum: ['resume_application','login','phone_verification','email_verification'], required: true }, destinationHash: { type: String, required: true }, codeHash: { type: String, required: true, select: false }, attempts: { type: Number, default: 0, min: 0 }, expiresAt: { type: Date, required: true }, consumedAt: Date }, [[{ expiresAt: 1 }, { expireAfterSeconds: 0 }], [{ applicationId: 1, purpose: 1, createdAt: -1 }, {}]]);
const LoginAttempt = simple('LoginAttempt', { identityHash: { type: String, required: true }, ipHash: String, userAgentHash: String, actorType: { type: String, enum: ['candidate','administrator'], required: true }, successful: { type: Boolean, required: true }, reason: String, expiresAt: { type: Date, required: true } }, [[{ expiresAt: 1 }, { expireAfterSeconds: 0 }], [{ identityHash: 1, successful: 1, createdAt: -1 }, {}]]);
const DocumentAccessLog = simple('DocumentAccessLog', { documentId: { ...ref('ApplicationDocument'), required: true }, actorId: { type: Schema.Types.ObjectId, required: true }, actorType: { type: String, enum: ['candidate','administrator','system'], required: true }, action: { type: String, enum: ['view','download','replace','delete'], required: true }, correlationId: String, ipHash: String }, [[{ documentId: 1, createdAt: -1 }, {}], [{ actorId: 1, createdAt: -1 }, {}]]);
const NotificationTemplate = simple('NotificationTemplate', { code: { type: String, required: true, uppercase: true, trim: true }, channel: { type: String, enum: ['in_app','email','sms'], required: true }, locale: { type: String, default: 'fr-GA' }, subject: String, body: { type: String, required: true }, variables: [{ type: String }], active: { type: Boolean, default: true }, version: { type: Number, default: 1, min: 1 } }, [[{ code: 1, channel: 1, locale: 1, version: 1 }, { unique: true }]]);
const SystemSetting = simple('SystemSetting', { key: { type: String, required: true, trim: true }, value: Schema.Types.Mixed, description: String, sensitive: { type: Boolean, default: false }, updatedBy: ref('Administrator') }, [[{ key: 1 }, { unique: true }]]);
const MigrationCheckpoint = simple('MigrationCheckpoint', { migration: { type: String, required: true }, entity: { type: String, required: true }, lastLegacyId: Number, batchNumber: { type: Number, min: 0, default: 0 }, status: { type: String, enum: ['pending','running','completed','failed'], default: 'pending' }, counts: { migrated: { type: Number, default: 0 }, skipped: { type: Number, default: 0 }, errors: { type: Number, default: 0 } }, error: String, completedAt: Date }, [[{ migration: 1, entity: 1 }, { unique: true }]]);
module.exports = { Establishment, Program, Subject, Contest, Administrator, Candidate, Application, ApplicationDocument, Payment, Notification, Message, SupportRequest, AuditLog, Session, Counter, Province, EducationLevel, ContestProgram, ProgramSubject, DocumentRequirement, Grade, PaymentEvent, Receipt, VerificationCode, LoginAttempt, DocumentAccessLog, NotificationTemplate, SystemSetting, MigrationCheckpoint };
